productName = "Tauri App"
version = "0.1.0"
identifier = "com.fuderis.tauri-app"

[build]
frontendDist = "../ui"

[app]
withGlobalTauri = true

[[app.windows]]
url = "views/main.html"
title = "Tauri App"
width = 950
height = 600
resizable = true
fullscreen = false

[app.security]
csp = ""

[bundle]
active = true
targets = "all"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
resources = [
]
